### ISSUE TITLE
tags management 

### ISSUE THREAD

**Issue by Rahilsiddique** [Rahilsiddique/next-blog#22]
Currently, there are too many tags on the /tags page.

step 1:

Create a drop-down to sort tags.
Sorting can be done in:
- alphabetical order
- ascending/descinding

step 2:

store the tags sorted state in url
Refer to [this](https://www.youtube.com/watch?v=ukpgxEemXsk) video for a better understanding.

**Comment by sirish123** [comment]
could u assign me this issue!

**Comment by Rahilsiddique** [comment]
sure @sirish123 go ahead, do let me know if you need any kind of help

**Comment by sirish123** [comment]
@Rahilsiddique i added the ascending and descending option for alphabetical order, and the state is managed through url. other sorting methods can be added on convenience by just making additions to the new sorting function
