### ISSUE TITLE
Fixing CSS for , Sort Order in Tags Page 

### ISSUE THREAD

**Issue by rahulsingh2312** [Rahilsiddique/next-blog#26]
currently:

![IMG-20231028-WA0046.jpg](https://github.com/Rahilsiddique/next-blog/assets/111289008/dba21ad9-3bc1-4614-9280-ff164b224acb)

expected : 

A normal drop down will look better in this currently it looks really sticked together

How to fix this issue :

go to /tag/page.tsx

and change that button to a drop down

suggested by - @rizzabh

**Comment by rahulsingh2312** [comment]
assign this to me

**Comment by Rahilsiddique** [comment]
cool
