### ISSUE TITLE
Add Error boundary 

### ISSUE THREAD

**Issue by Rahilsiddique** [Rahilsiddique/next-blog#6]
currently in the main link when a user tries to access anything out of the realm of this project they get the 500 internal server error 
instead they should be greeted with `404` error or `something went missing` 

![image](https://github.com/Rahilsiddique/next-blog/assets/75086395/63e40f88-cc93-42b2-b6f3-cee836b3ec11)

add an error boundary to show a custom error message

**Comment by rupeshghosh10** [comment]
Hi @Rahilsiddique, I want to work on this

**Comment by Rahilsiddique** [comment]
@rupeshghosh10  sure, if you need any kind of assistance do let me konw
