### ISSUE TITLE
Create a component for authors 

### ISSUE THREAD

**Issue by Rahilsiddique** [Rahilsiddique/next-blog#7]
currently all the authors are listed as a list of simple string
![image](https://github.com/Rahilsiddique/next-blog/assets/75086395/838cc38c-78f6-48c4-a225-0428bbcf768c)
### create a component similar to `PostPreview` in `src --> component --> PostPreview.tsx`
- along with authors' name also display the number of posts created by that author

**Comment by amitsuthar69** [comment]
I would like to work on this issue.

This is how I'd define the author card's skeleton :
1. An author's image if not then it's initial.
2. No. of blogs by him.
3. Add user pfp to blog preview section.

All these card would be rendered on authors route.
Suggest me if more things to be added in.
