### ISSUE TITLE
Create about us section 

### ISSUE THREAD

**Issue by Rahilsiddique** [Rahilsiddique/next-blog#8]
Currently the about us section is pretty  empty try to add content in about us section 
things to take into consideration while working on this issue 
- make sure your content is in `markdown.md` format 
- add relevant images 
- refer how blogs are rendered in `src --> app --> [...slug] --> page.tsx ` for better understanding

**Comment by Durgeshsejekar** [comment]
I want to work on this issue so please can u assign me.

**Comment by Rahilsiddique** [comment]
sure @Durgeshsejeka, go ahead, do let me know if you need any help

**Comment by Rahilsiddique** [comment]
hey @Durgeshsejekar, any progress so far? we want to close this issue ASAP

**Comment by rizzabh** [comment]
Can I work on this @Rahilsiddique ? :D
