### ISSUE TITLE
Create a nice footer

### ISSUE THREAD

**Issue by Rahilsiddique** [Rahilsiddique/next-blog#9]
create a nice footer 
as of now its just a simple component add some styles to it make it more functional 
to add styles edit the following component:
`src --> component --> Footer.tsx`

**Comment by VishnuAmit** [comment]
Hey. Would love to take this task if its still available for me :)

**Comment by Rahilsiddique** [comment]
hey @VishnuAmit, sure no one, is currently working on this issue, you can go ahead, do let me know if you need any sort of help

**Comment by VishnuAmit** [comment]
Yea thanks buddy

**Comment by VishnuAmit** [comment]
hey @Rahilsiddique . Done with the footer and I hope you like it and accept it under Hacktoberfest 23

**Comment by VishnuAmit** [comment]
Hey @Rahilsiddique, I have done the updates with the footer. Check once
footer inside body tag
Separate Svg folder for icons
